shell /usr/bin/fish

font_size 14

cursor_trail 3
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 2

#change the binds of changing tabs
map alt+e new_tab
map alt+a previous_tab
map alt+d next_tab
map alt+q close_tab
map alt+1  nth_tab 1
map alt+2  nth_tab 2
map alt+3  nth_tab 3
map alt+4  nth_tab 4
map alt+5  nth_tab 5
map alt+6  nth_tab 6
map alt+7  nth_tab 7
map alt+8  nth_tab 8
map alt+9  nth_tab 9
map alt+w new_window
map alt+s neighboring_window

# BEGIN_KITTY_THEME
# Matugen
include current-theme.conf
# END_KITTY_THEME
