[config]

[config.wallpaper]
command = "awww img {{ image }} --transition-type center"
set = true

[templates.fuzzel]
input_path = '~/.config/matugen/templates/fuzzel.ini'
output_path = '~/.config/fuzzel/colors.ini'


[templates.helix]
input_path = '~/.config/matugen/templates/helix.toml'
output_path = '~/.config/helix/themes/matugen.toml'

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty-colors.conf'
output_path = '~/.config/kitty/themes/Matugen.conf'
post_hook = "kitty +kitten themes --reload-in=all Matugen"

[templates.mako]
input_path = '~/.config/matugen/templates/mako'
output_path = '~/.config/mako/mako-colors'
post_hook = 'makoctl reload'

[templates.niri]
input_path = '~/.config/matugen/templates/niri-colors.kdl'
output_path = '~/.config/niri/colors.kdl'
post_hook = 'niri msg action load-config-file'

[templates.prismlauncher]
input_path = '~/.config/matugen/templates/prismlauncher.json'
output_path = '~/.local/share/PrismLauncher/themes/Matugen/theme.json'

[templates.yazi]
input_path = '~/.config/matugen/templates/yazi-theme.toml'
output_path = '~/.config/yazi/theme.toml'

# [templates.waybar]
# input_path = '~/.config/matugen/templates/colors.css'
# output_path = '~/.config/waybar/colors.css'
# post_hook = 'pkill -SIGUSR2 waybar'

[templates.musicfox]
input_path = '~/.config/matugen/templates/musicfox.toml'
output_path = '~/.config/go-musicfox/themes/musicfox.toml'
